# Build Stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
ARG VITE_DEMO_ADMIN_EMAIL
ENV VITE_DEMO_ADMIN_EMAIL=$VITE_DEMO_ADMIN_EMAIL
ARG VITE_DEMO_ADMIN_PASSWORD
ENV VITE_DEMO_ADMIN_PASSWORD=$VITE_DEMO_ADMIN_PASSWORD
ARG VITE_DEMO_USER_EMAIL
ENV VITE_DEMO_USER_EMAIL=$VITE_DEMO_USER_EMAIL
ARG VITE_DEMO_USER_PASSWORD
ENV VITE_DEMO_USER_PASSWORD=$VITE_DEMO_USER_PASSWORD
ARG NUXT_ENV_MIDTRANS_CLIENT_KEY
ENV NUXT_ENV_MIDTRANS_CLIENT_KEY=$NUXT_ENV_MIDTRANS_CLIENT_KEY

RUN npm run build

# Serve Stage

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]